<a href="https://colab.research.google.com/github/zohaibkhanzohaibi/OEC_Japan_IT_Class/blob/master/class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def multiplier(factor):
  def multiply(num):
    return num * factor
  return multiply
double = multiplier(2)
print(double(9))

18


In [1]:
def factorial(n):
  """Return the factorial of n, an exact integer >= 0."""
  if n == 0:
    return 1
  if n == 1:
    return 1
  return n * factorial(n-1)
factorial(5)

120

In [6]:
help(factorial)

Help on function factorial in module __main__:

factorial(n)
    Return the factorial of n, an exact integer >= 0.



In [8]:
z = 5
def modify_global():
  global z
  z = 10
modify_global()
print(z)

10


In [9]:
def outer():
  x = "local"
  def inner():
    nonlocal x
    x = "nonlocal"
  inner()
  print("outer:", x)
outer()

inner: nonlocal
outer: nonlocal


In [10]:
import numpy as np

In [11]:
#numpy arrays are faster and memory efficient than python lists

py_list = [1, 2, 3, 4]
np_arr = np.array(py_list)
print(type(np_arr))
print(type(py_list))

<class 'numpy.ndarray'>
<class 'list'>


In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2d.ndim

2

In [18]:
zeros2d = np.zeros((2, 3))
zeros2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
ones3d = np.ones((3, 3))
ones3d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
any_no = np.full((3,3), 54)
any_no

array([[54, 54, 54],
       [54, 54, 54],
       [54, 54, 54]])

In [24]:
#evenly spaced value between a range (start, end, number of spaces)
linspace_arr = np.linspace(1, 10, 6)
linspace_arr

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [32]:
#(start, end , stepvalue(default = 1))
range_array = np.arange(1, 10, 2)
range_array

array([1, 3, 5, 7, 9])

In [35]:
random_array = np.random.rand(3, 3) * 10
random_array

array([[3.43223051, 9.97290306, 5.04997716],
       [8.02854452, 1.15178032, 5.3052381 ],
       [5.15660065, 9.34954095, 5.33631005]])

In [40]:
#(start, end, (row, col))
random_int_arr = np.random.randint(1, 100, (3, 3))
random_int_arr

array([[12,  1, 91],
       [40, 83, 88],
       [78, 49, 70]])

In [43]:
print(random_int_arr.shape)
print(random_int_arr.ndim)
print(random_int_arr.size)

(3, 3)
2
9


In [47]:
np_arr = np.array([1, 2, 3, 4])
print(np_arr)
np_arr = np_arr.reshape((2, 2))
print(np_arr)

[1 2 3 4]
[[1 2]
 [3 4]]


In [48]:
arr = np.array([0, np.pi/2, np.pi])
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[0.         1.25331414 1.77245385]


In [49]:
help(np.exp)

Help on ufunc:

exp = <ufunc 'exp'>
    exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Calculate the exponential of all elements in the input array.
    
    Parameters
    ----------
    x : array_like
        Input values.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [50]:
np.sum(arr)

4.71238898038469

In [52]:
arr = np.random.randint(1, 100, (4, 4))
print(arr)

[[66 82 85 17]
 [71 87 91  7]
 [83 77 93 49]
 [66 82 41 62]]


In [68]:
print(arr[0:2, :2])
print(arr[::2, ::2]) #every second element
print(arr[:, ::-1]) #reverse
print(arr[::-2]) #in reverse every second row
print(arr[::-2, ::-2])

[[66 82]
 [71 87]]
[[66 85]
 [83 93]]
[[17 85 82 66]
 [ 7 91 87 71]
 [49 93 77 83]
 [62 41 82 66]]
[[66 82 41 62]
 [71 87 91  7]]
[[62 82]
 [ 7 87]]


In [69]:
result = np.where(arr>70)
print(result)

(array([0, 0, 1, 1, 1, 2, 2, 2, 3]), array([1, 2, 0, 1, 2, 0, 1, 2, 1]))


In [70]:
print(arr[result])

[82 85 71 87 91 83 77 93 82]


In [71]:
arr[np.where(arr <70)]

array([66, 17,  7, 49, 66, 41, 62])

In [77]:
take_arr = np.take(arr, [0, 1])
take_arr

array([66, 82])